package com.zemoso.springbootassignment.productservice.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;


// Used to specify that this java class is entity which is table in relation database
@Entity
// Used to specify the name of the table
@Table(name = "products")

// reducing the code by automatically generated code like default constructor
// parameterized constructor, getter and setter etc.

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Product {

    // We are defining primary key using @Id annotation
    @Id
    /*
        GeneratedValue used to indicate that the value is automatically
        generated by database
        Strategy specifies that what will be the generation type of id
        GenerationType.IDENTITY means it is auto incremented value
    */
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private String productImage;
    private String name;
    private String seller;
    private String description;
    private BigDecimal price;

}
